// <auto-generated />
using System;
using CvViewer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CvViewer.DataAccess.Migrations;

[DbContext(typeof(CvContext))]
[Migration("20251201231206_InitialCreate")]
partial class Baseline
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("CvViewer.DataAccess.Entities.AuteurEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<string>("Achternaam")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("ExternalId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Tussenvoegsel")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Voornaam")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Auteurs");
            });

        modelBuilder.Entity("CvViewer.DataAccess.Entities.CertificaatInstanceEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<DateOnly>("DatumAfgifte")
                    .HasColumnType("date");

                b.Property<string>("Naam")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Uitgever")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Url")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateOnly?>("Verloopdatum")
                    .HasColumnType("date");

                b.HasKey("Id");

                b.ToTable("CertificaatInstances");
            });

        modelBuilder.Entity("CvViewer.DataAccess.Entities.CvEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<long>("AuteurId")
                    .HasColumnType("bigint");

                b.Property<Guid>("ExternalId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Inleiding")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<bool>("IsFavorite")
                    .HasColumnType("bit");

                b.Property<DateTime>("LastUpdated")
                    .HasColumnType("datetime2");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.Property<string>("VaardigheidInstances")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("AuteurId");

                b.ToTable("Cvs");
            });

        modelBuilder.Entity("CvViewer.DataAccess.Entities.OpleidingInstanceEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<string>("Beschrijving")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateOnly>("Einddatum")
                    .HasColumnType("date");

                b.Property<string>("Instituut")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Naam")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateOnly?>("Startdatum")
                    .HasColumnType("date");

                b.HasKey("Id");

                b.ToTable("OpleidingInstances");
            });

        modelBuilder.Entity("CvViewer.DataAccess.Entities.WerkervaringInstanceEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<string>("Beschrijving")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateOnly?>("Einddatum")
                    .HasColumnType("date");

                b.Property<string>("Organisatie")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Rol")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateOnly>("Startdatum")
                    .HasColumnType("date");

                b.HasKey("Id");

                b.ToTable("WerkervaringInstances");
            });

        modelBuilder.Entity("CvViewer.DataAccess.Entities.AuteurEntity", b =>
            {
                b.OwnsOne("CvViewer.DataAccess.Entities.AdresEntity", "Adres", b1 =>
                    {
                        b1.Property<long>("AuteurEntityId")
                            .HasColumnType("bigint");

                        b1.Property<string>("Huisnummer")
                            .IsRequired()
                            .HasColumnType("nvarchar(max)");

                        b1.Property<string>("Land")
                            .IsRequired()
                            .HasMaxLength(100)
                            .HasColumnType("nvarchar(100)");

                        b1.Property<string>("Plaats")
                            .IsRequired()
                            .HasMaxLength(100)
                            .HasColumnType("nvarchar(100)");

                        b1.Property<string>("Postcode")
                            .IsRequired()
                            .HasMaxLength(20)
                            .HasColumnType("nvarchar(20)");

                        b1.Property<string>("Straat")
                            .IsRequired()
                            .HasMaxLength(200)
                            .HasColumnType("nvarchar(200)");

                        b1.HasKey("AuteurEntityId");

                        b1.ToTable("Auteurs");

                        b1.WithOwner()
                            .HasForeignKey("AuteurEntityId");
                    });

                b.OwnsOne("CvViewer.DataAccess.Entities.ContactgegevensEntity", "Contactgegevens", b1 =>
                    {
                        b1.Property<long>("AuteurEntityId")
                            .HasColumnType("bigint");

                        b1.Property<string>("Email")
                            .HasMaxLength(256)
                            .HasColumnType("nvarchar(256)");

                        b1.Property<string>("LinkedInUrl")
                            .HasMaxLength(256)
                            .HasColumnType("nvarchar(256)");

                        b1.Property<string>("Telefoonnummer")
                            .HasMaxLength(50)
                            .HasColumnType("nvarchar(50)");

                        b1.HasKey("AuteurEntityId");

                        b1.ToTable("Auteurs");

                        b1.WithOwner()
                            .HasForeignKey("AuteurEntityId");
                    });

                b.Navigation("Adres")
                    .IsRequired();

                b.Navigation("Contactgegevens")
                    .IsRequired();
            });

        modelBuilder.Entity("CvViewer.DataAccess.Entities.CvEntity", b =>
            {
                b.HasOne("CvViewer.DataAccess.Entities.AuteurEntity", "Auteur")
                    .WithMany("Cvs")
                    .HasForeignKey("AuteurId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.OwnsOne("CvViewer.DataAccess.Snapshots.AdresSnapshot", "AdresSnapshot", b1 =>
                    {
                        b1.Property<int>("CvEntityId")
                            .HasColumnType("int");

                        b1.Property<string>("Huisnummer")
                            .HasColumnType("nvarchar(max)");

                        b1.Property<string>("Land")
                            .HasMaxLength(100)
                            .HasColumnType("nvarchar(100)");

                        b1.Property<string>("Postcode")
                            .HasMaxLength(20)
                            .HasColumnType("nvarchar(20)");

                        b1.Property<string>("Stad")
                            .HasMaxLength(100)
                            .HasColumnType("nvarchar(100)");

                        b1.Property<string>("Straat")
                            .HasMaxLength(200)
                            .HasColumnType("nvarchar(200)");

                        b1.HasKey("CvEntityId");

                        b1.ToTable("Cvs");

                        b1.WithOwner()
                            .HasForeignKey("CvEntityId");
                    });

                b.OwnsOne("CvViewer.DataAccess.Snapshots.ContactgegevensSnapshot", "ContactgegevensSnapshot", b1 =>
                    {
                        b1.Property<int>("CvEntityId")
                            .HasColumnType("int");

                        b1.Property<string>("Email")
                            .HasMaxLength(256)
                            .HasColumnType("nvarchar(256)");

                        b1.Property<string>("LinkedInUrl")
                            .HasMaxLength(256)
                            .HasColumnType("nvarchar(256)");

                        b1.Property<string>("Telefoonnummer")
                            .HasMaxLength(50)
                            .HasColumnType("nvarchar(50)");

                        b1.HasKey("CvEntityId");

                        b1.ToTable("Cvs");

                        b1.WithOwner()
                            .HasForeignKey("CvEntityId");
                    });

                b.OwnsMany("CvViewer.DataAccess.Snapshots.CertificaatInstanceSnapshot", "CertificaatInstances", b1 =>
                    {
                        b1.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("int");

                        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                        b1.Property<int>("CvId")
                            .HasColumnType("int");

                        b1.Property<DateOnly?>("DatumAfgifte")
                            .HasColumnType("date");

                        b1.Property<string>("Naam")
                            .HasColumnType("nvarchar(max)");

                        b1.Property<string>("Uitgever")
                            .HasColumnType("nvarchar(max)");

                        b1.Property<string>("Url")
                            .HasColumnType("nvarchar(max)");

                        b1.Property<DateOnly?>("Verloopdatum")
                            .HasColumnType("date");

                        b1.HasKey("Id");

                        b1.HasIndex("CvId");

                        b1.ToTable("CertificaatInstanceSnapshot");

                        b1.WithOwner()
                            .HasForeignKey("CvId");
                    });

                b.OwnsMany("CvViewer.DataAccess.Snapshots.OpleidingInstanceSnapshot", "OpleidingInstances", b1 =>
                    {
                        b1.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("int");

                        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                        b1.Property<string>("Beschrijving")
                            .HasColumnType("nvarchar(max)");

                        b1.Property<int>("CvId")
                            .HasColumnType("int");

                        b1.Property<DateOnly?>("Einddatum")
                            .HasColumnType("date");

                        b1.Property<string>("Instituut")
                            .HasColumnType("nvarchar(max)");

                        b1.Property<DateOnly?>("Startdatum")
                            .HasColumnType("date");

                        b1.Property<string>("Title")
                            .HasColumnType("nvarchar(max)");

                        b1.HasKey("Id");

                        b1.HasIndex("CvId");

                        b1.ToTable("OpleidingInstanceSnapshot");

                        b1.WithOwner()
                            .HasForeignKey("CvId");
                    });

                b.OwnsMany("CvViewer.DataAccess.Snapshots.WerkervaringInstanceSnapshot", "WerkervaringInstances", b1 =>
                    {
                        b1.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("int");

                        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                        b1.Property<string>("Bedrijfsnaam")
                            .IsRequired()
                            .HasColumnType("nvarchar(max)");

                        b1.Property<string>("Beschrijving")
                            .HasColumnType("nvarchar(max)");

                        b1.Property<int>("CvId")
                            .HasColumnType("int");

                        b1.Property<DateOnly?>("Einddatum")
                            .HasColumnType("date");

                        b1.Property<string>("Functietitel")
                            .IsRequired()
                            .HasColumnType("nvarchar(max)");

                        b1.Property<string>("Locatie")
                            .HasColumnType("nvarchar(max)");

                        b1.Property<DateOnly>("Startdatum")
                            .HasColumnType("date");

                        b1.HasKey("Id");

                        b1.HasIndex("CvId");

                        b1.ToTable("WerkervaringInstanceSnapshot");

                        b1.WithOwner()
                            .HasForeignKey("CvId");
                    });

                b.Navigation("AdresSnapshot");

                b.Navigation("Auteur");

                b.Navigation("CertificaatInstances");

                b.Navigation("ContactgegevensSnapshot");

                b.Navigation("OpleidingInstances");

                b.Navigation("WerkervaringInstances");
            });

        modelBuilder.Entity("CvViewer.DataAccess.Entities.AuteurEntity", b =>
            {
                b.Navigation("Cvs");
            });
#pragma warning restore 612, 618
    }
}
